"""add indexes

Revision ID: a06b901d7580
Revises: c51809d0324f
Create Date: 2026-06-14 12:55:10.622262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06b901d7580'
down_revision: Union[str, Sequence[str], None] = 'c51809d0324f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_testattempts_test_id_score_created_at',
        'testattempts',
        ['test_id', sa.text('score DESC'), sa.text('created_at ASC')]
    )

    op.create_index(
        'ix_testattempts_user_id',
        'testattempts',
        ['user_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_testattempts_test_id_score_created_at', table_name='testattempts')
    op.drop_index('ix_testattempts_user_id', table_name='testattempts')
    # ### end Alembic commands ###
